config/routes.rb
FetchFavorites::Application.routes.draw do
  resources :feeds

  resources :favorites

  match 'feedfavorites/:feed_id' => 'favorites#feedfavorites'

  match 'fetch' => 'favorites#fetch'

  root :to => "favorites#index"

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates_uniqueness_of :id_str
  belongs_to :feed # feed_id
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
    @favorites = Favorite.all
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  def feedfavorites
    @favorites = Favorite.all
    render :partial => "feedfavorites"
    #respond_to do |format|
      #format.html # favorites.html.erb
    #end
  end

  def fetch
    @feeds = Feed.all
    @feeds.each do |feed|
      jsondata = open(feed.url, :proxy => "http://gatekeeper-w.mitre.org:80").read
      #jsondata = open(feed.url).read
      data = ActiveSupport::JSON.decode(jsondata)
      csv = []
      CSV.open("./public/#{feed.id}.csv", "w") do |csv|
      csv << ["feed.url", "id_str", "in_reply_to_status_id", "user_id_str", "verified", "friends_count", "is_translator", "statuses_count", "name", "favourites_count", "profile_image_url", "utc_offset", "location", "description", "screen_name", "lang", "homepage_url", "listed_count", "time_zone", "created_at", "user_created_at", "followers_count", "user_id", "geo_enabled", "following", "text", "in_reply_to_user_id", "retweet_count", "place", "favorited", "in_reply_to_status_id_str", "in_reply_to_screen_name", "source", "in_reply_to_user_id_str", "retweeted", "coordinates", "geo", "latitude", "longitude", "country", "country_code", "place_full_name"]
      data.each do |item|
        if item["place"].nil?
          country = country_code = place_full_name = ""
        else
          country = item["place"]["country"]
          country_code = item["place"]["country_code"]
          place_full_name = item["place"]["full_name"]         
        end
        if item["geo"].nil?
          latitude = longitude = place_full_name = ""
        else
          latitude = item["geo"]["coordinates"][0]
          longitude = item["geo"]["coordinates"][1]  
        end
        
        @favorite = Favorite.new(:feed_id => feed.id, :source_url => feed.url, :id_str => item["id_str"], :in_reply_to_status_id => item["in_reply_to_status_id"], :user_id_str => item["user"]["id_str"], :verified => item["user"]["verified"], :friends_count => item["user"]["friends_count"], :is_translator => item["user"]["is_translator"], :statuses_count => item["user"]["statuses_count"], :name => item["user"]["name"], :favourites_count => item["user"]["favourites_count"], :profile_image_url => item["user"]["profile_image_url"], :utc_offset => item["user"]["utc_offset"], :location => item["user"]["location"], :description => item["user"]["description"], :screen_name => item["user"]["screen_name"], :lang => item["user"]["lang"], :homepage_url => item["user"]["url"], :listed_count => item["user"]["listed_count"], :time_zone => item["user"]["time_zone"], :twitter_created_at => item["created_at"], :user_created_at => item["user"]["created_at"],:followers_count => item["user"]["followers_count"], :user_id => item["user"]["id"], :geo_enabled => item["user"]["geo_enabled"], :following => item["user"]["following"], :text => item["text"], :in_reply_to_user_id => item["in_reply_to_user_id"], :retweet_count => item["retweet_count"], :place => item["place"], :favorited => item["favorited"], :in_reply_to_status_id_str => item["in_reply_to_status_id_str"], :in_reply_to_screen_name => item["in_reply_to_screen_name"], :source => item["source"], :in_reply_to_user_id_str => item["in_reply_to_user_id_str"], :coordinates => item["coordinates"], :geo => item["geo"],  :retweeted => item["retweeted"], :latitude => latitude, :longitude => longitude, :country => country, :country_code => country_code, :place_full_name => place_full_name)
        csv << [feed.url, item["id_str"], item["in_reply_to_status_id"], item["user"]["id_str"], item["user"]["verified"], item["user"]["friends_count"], item["user"]["is_translator"], item["user"]["statuses_count"], item["user"]["name"], item["user"]["favourites_count"], item["user"]["profile_image_url"], item["user"]["utc_offset"], item["user"]["location"], item["user"]["description"], item["user"]["screen_name"], item["user"]["lang"], item["user"]["url"], item["user"]["listed_count"], item["user"]["time_zone"], item["created_at"], item["user"]["created_at"] ,item["user"]["followers_count"], item["user"]["id"], item["user"]["geo_enabled"], item["user"]["following"], item["text"], item["in_reply_to_user_id"], item["retweet_count"], item["place"], item["favorited"], item["in_reply_to_status_id_str"], item["in_reply_to_screen_name"], item["source"], item["in_reply_to_user_id_str"], item["retweeted"], item["coordinates"], item["geo"], latitude, longitude, country,  country_code, place_full_name]
        @favorite.save
      end
    end
    end
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.xml
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.xml
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.xml
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.xml
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to(@feed, :notice => 'Feed was successfully created.') }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.xml
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to(@feed, :notice => 'Feed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.xml
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to(feeds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/favorites/_favorites.erb
<% @favorites.each do |favorite| %>
<% if favorite.source_url == @sourcefeed.url %>
<p><strong>Tweet: </strong><%= favorite.text %></p>
<p><strong>Name: </strong><%= favorite.name %> (<%= favorite.screen_name %>)</p>
<p><strong>Tweet Date: </strong><%= favorite.twitter_created_at %></p>
<% if favorite.latitude.blank? %>
<% else %>
</div>
<p><a href="http://maps.google.com/maps?q=<%= favorite.latitude %>+<%= favorite.longitude %>">Location on Google Map</a></p>
<% end %>
<p class = "link_banner"><%= link_to 'Show / Add Note', favorite %> - <%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></p>
<% end %>
<% end %>

app/views/favorites/_feedfavorites.erb
<% @favorites.each do |favorite| %>
<% if favorite.feed_id.to_s() == params[:feed_id] %>
<div><strong>Tweet: </strong><%= favorite.text %></p>
<div><strong>Name: </strong><%= favorite.name %> (<%= favorite.screen_name %>)</p>
<div><strong>Tweet Date: </strong><%= favorite.twitter_created_at %></p>
<% if !favorite.latitude.blank? %>
</div>
<div><a href="http://maps.google.com/maps?q=<%= favorite.latitude %>+<%= favorite.longitude %>">Location on Google Map</a></p>
<% end %>
<p class = "link_banner"><%= link_to 'Show / Add Note', favorite %> - <%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></p>
<% end %>
<% end %>

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_str %><br />
    <%= f.text_field :id_str %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_status_id %><br />
    <%= f.text_field :in_reply_to_status_id %>
  </div>
  <div class="field">
    <%= f.label :user_id_str %><br />
    <%= f.text_field :user_id_str %>
  </div>
  <div class="field">
    <%= f.label :verified %><br />
    <%= f.text_field :verified %>
  </div>
  <div class="field">
    <%= f.label :friends_count %><br />
    <%= f.text_field :friends_count %>
  </div>
  <div class="field">
    <%= f.label :is_translator %><br />
    <%= f.text_field :is_translator %>
  </div>
  <div class="field">
    <%= f.label :statuses_count %><br />
    <%= f.text_field :statuses_count %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :favourites_count %><br />
    <%= f.text_field :favourites_count %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url %><br />
    <%= f.text_field :profile_image_url %>
  </div>
  <div class="field">
    <%= f.label :utc_offset %><br />
    <%= f.text_field :utc_offset %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :lang %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :homepage_url %><br />
    <%= f.text_field :homepage_url %>
  </div>
  <div class="field">
    <%= f.label :listed_count %><br />
    <%= f.text_field :listed_count %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.text_field :time_zone %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :followers_count %><br />
    <%= f.text_field :followers_count %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :geo_enabled %><br />
    <%= f.text_field :geo_enabled %>
  </div>
  <div class="field">
    <%= f.label :following %><br />
    <%= f.text_field :following %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_user_id %><br />
    <%= f.text_field :in_reply_to_user_id %>
  </div>
  <div class="field">
    <%= f.label :retweet_count %><br />
    <%= f.text_field :retweet_count %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :favorited %><br />
    <%= f.text_field :favorited %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_status_id_str %><br />
    <%= f.text_field :in_reply_to_status_id_str %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_screen_name %><br />
    <%= f.text_field :in_reply_to_screen_name %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_user_id_str %><br />
    <%= f.text_field :in_reply_to_user_id_str %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br />
    <%= f.text_field :coordinates %>
  </div>
  <div class="field">
    <%= f.label :geo %><br />
    <%= f.text_field :geo %>
  </div>
  <div class="field">
    <%= f.label :retweeted %><br />
    <%= f.text_field :retweeted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/fetch.erb
<%= link_to 'Back', favorites_path %>

<p>Favorites fetched</p>

app/views/favorites/index.html.erb
<script type="text/javascript">
$(document).ready(function(){
<% @feeds.each do |@sourcefeed| %>
  $("h2#title_<%= @sourcefeed.id %>").click(function(){
    $("div#favorites_<%= @sourcefeed.id %>").hide().load('<%= url_for (:action=> 'feedfavorites', :feed_id => @sourcefeed.id) %>', function() {
		$(this).slideDown("slow") });
  	$("h2#title_<%= @sourcefeed.id %>").unbind()
  	$("h2#title_<%= @sourcefeed.id %>").click(function(){
    	$("div#favorites_<%= @sourcefeed.id %>").slideToggle("slow")
	});
  });
<% end %>
});
</script>


<h1>Fetched Favorites</h1>
<p><%= link_to 'Fetch Favorites', fetch_path %> - <%= link_to 'Followed Feeds', feeds_path %></p>
<p><strong>Download CSV files: </strong><% @feeds.each do |feed| %>
<a href="<%= feed.id %>.csv"><%= feed.id %>.csv</a>
<% end %>
</p>
<% @feeds.each do |@sourcefeed| %>
<h2 class="sourcefeed_title" id="title_<%= @sourcefeed.id %>"><%= @sourcefeed.url %></h2>
<div class="wrapper">
<div class="favorites" id="favorites_<%= @sourcefeed.id %>">
</div>
</div>
<% end %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<%= link_to 'Back', favorites_path %>



<p id="notice"><%= notice %></p>

<div class="profile_pic"><img src="<%= @favorite.profile_image_url %>" /></div>
<h3><%= @favorite.screen_name %>: <%= @favorite.text %></h3>
<p><a href="http://twitter.com/#!/<%= @favorite.screen_name %>/status/<%= @favorite.id_str %>">original tweet link</a> - <a href="http://twitter.com/<%= @favorite.screen_name %>">user profile</a></p>



<% if @favorite.latitude.blank? %>
<% else %>
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?q=<%= @favorite.latitude %>+<%= @favorite.longitude %>&amp;output=embed"></iframe>
<% end %>

<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="notes">
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :cols => 60, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Feed ID</h2>
<p>
  <b>Feed id:</b>
  <%= @favorite.feed_id %>
</p>

<h2>Tweet Info</h2>
<p>
  <b>Tweet Created at:</b>
  <%= @favorite.created_at %>
</p>

<p>
  <b>Tweet Id:</b>
  <%= @favorite.id_str %>
</p>

<p>
  <b>In reply to status:</b>
  <%= @favorite.in_reply_to_status_id %>
</p>

<p>
  <b>In reply to user:</b>
  <%= @favorite.in_reply_to_user_id %>
</p>

<p>
  <b>Retweet count:</b>
  <%= @favorite.retweet_count %>
</p>

<p>
  <b>Favorited:</b>
  <%= @favorite.favorited %>
</p>

<p>
  <b>Place:</b>
  <a href="http://maps.google.com/maps?q=<%= @favorite.place_full_name %>"><%= @favorite.place_full_name %></a>
</p>

<p>
  <b>Latitude:</b>
  <%= @favorite.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @favorite.longitude %>
</p>

<p>
  <b>Retweeted:</b>
  <%= @favorite.retweeted %>
</p>

<p>
  <b>In reply to status id str:</b>
  <%= @favorite.in_reply_to_status_id_str %>
</p>

<p>
  <b>In reply to screen name:</b>
  <%= @favorite.in_reply_to_screen_name %>
</p>

<p>
  <b>In reply to user id str:</b>
  <%= @favorite.in_reply_to_user_id_str %>
</p>

<p>
  <b>Source:</b>
  <%= @favorite.source %>
</p>

<h2>User Info</h2>

<p>
  <b>Name:</b>
  <%= @favorite.name %>
</p>

<p>
  <b>Description:</b>
  <%= @favorite.description %>
</p>


<p>
  <b>Location:</b>
  <a href="http://maps.google.com/maps?q=<%= @favorite.location %>"><%= @favorite.location %></a>
</p>


<p>
  <b>Homepage url:</b>
  <%= link_to @favorite.homepage_url, @favorite.homepage_url %>
</p>

<p>
  <b>User Account Created at:</b>
  <%= @favorite.user_created_at %>
</p>

<p>
  <b>Followers count:</b>
  <%= @favorite.followers_count %>
</p>

<p>
  <b>Listed count:</b>
  <%= @favorite.listed_count %>
</p>

<p>
  <b>Time zone:</b>
  <%= @favorite.time_zone %>
</p>

<p>
  <b>User id str:</b>
  <%= @favorite.user_id_str %>
</p>

<p>
  <b>Verified:</b>
  <%= @favorite.verified %>
</p>

<p>
  <b>Friends count:</b>
  <%= @favorite.friends_count %>
</p>

<p>
  <b>Statuses count:</b>
  <%= @favorite.statuses_count %>
</p>

<p>
  <b>Favourites count:</b>
  <%= @favorite.favourites_count %>
</p>

<p>
  <b>Utc offset:</b>
  <%= @favorite.utc_offset %>
</p>

<p>
  <b>Lang:</b>
  <%= @favorite.lang %>
</p>

<p>
  <b>Country:</b>
  <%= @favorite.country %>
</p>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<%= link_to 'Back', favorites_path %>

<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.url %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FetchFavorites</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery.js" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
<%= yield %>

</div>
</body>
</html>